module.exports = {
  en: {
    langName: "Engish",
    hello1: "Hi",
    hello2: "Welcome to the anonymous chat, your anonymity is valued here 👌\nLet's not hesitate, let's start the search, shall we? /search 🔎",
    hello01: "What is your gender?",
    info: "How does it work? It's simple, you and other people are looking for an interlocutor, after a successful search, you and another random person start a dialogue, after that it all depends on you and your interlocutor!\nLet's not hesitate, let's start the search, shall we? /search 🔎",
    undef: "Unknown commands 😟",
    search: "Seaching... 🎲",
    searchSucc: "Interlocutor found 👤\n\n🚫 Complain about the interlocutor /report \n🔄 Find a new interlocutor /next \n⛔️ Stop the dialogue /stop",
    searchStop: "Dialogue stopped 👋 \n\n🚫 Complain about the other party /report\n🔎 Start search /search",
    search4: "",
    search5: "",
    search6: "",
    search7: "",
  },
  ua: {
    langName: "Ukrainian",
    hello1: "Привіт",
    hello2: "Ласкаво просимо до анонімного чату, тут цінують вашу анонімність 👌\nНе зволікатимемо, приступимо до пошуку? /search 🔎",
    hello01: "Яка ваша стать?",
    info: "Як це працює? Все просто, ти та інші люди шукають співрозмовника, після успішного пошуку ви та інша випадкова людина починаєте діалог, після все залежить від вас та вашого співрозмовника! \nНе зволікатимемо, приступимо до пошуку? /search 🔎",
    undef: "Невідома команда 😟",
    search: "Пошук... 🎲",
    searchSucc: "Співрозмовника знайдено 👤\n\n🚫 Поскаржитися на співрозмовника /report \n🔄 Знайти нового співрозмовника /next \n⛔️ Зупинити діалог /stop",
    searchStop: "Діалог зупинено 👋 \n\n🚫 Поскаржитися на співрозмовника /report\n🔎 Розпочати пошук /search",
    search4: "",
    search5: "",
    search6: "",
    search7: "",
  },
  ru: {
    langName: "Russian",
    hello1: "Привет",
    hello2: "Добро пожаловать в анонимный чат, здесь ценят вашу анонимность 👌\nНе будем медлить, приступим к поиску? /search 🔎",
    hello01: "Какой ваш пол?",
    info: "Как это работает? Всё просто, ты и другие люди ищут собеседника, после успешного поиска вы и другой случайный человек начинаете диалог, после всё зависит от вас и вашего собеседника! \nНе будем медлить, приступим к поиску? /search 🔎",
    undef: "Неизвестная команда 😟",
    search: "Идёт поиск... 🎲",
    searchSucc: "Собеседник найден 👤\n\n🚫 Пожаловаться на собеседника /report \n🔄 Найти нового собеседника /next \n⛔️ Остановить диалог /stop",
    searchStop: "Диалог остановлен 👋 \n\n🚫 Пожаловаться на собеседника /report\n🔎 Начать поиск /search",
    search5: "",
    search6: "",
    search7: "",
  },
}
